In [ ]:
# ADVANCED PYTHON

In [1]:
#introduction to 3rd party libraries of python

In [2]:
#library: collection of pgms

In [ ]:
#INTRODUCTION TO NUMPY: It stands for numerical python 

In [3]:
# installation of Numpy:


In [4]:
!pip install numpy

In [ ]:
# By default anaconda has Numpy (jupyter notebook)

In [5]:
# Datatypes in Numpy : ndarray ----> N dimensional arrays 

In [6]:
# CONCEPTS:

In [7]:
#1. creating an array from a regular python list:


In [ ]:
import numpy as np #syntax np ----> alias name globally standard followed

In [8]:
array_one = np.array([1,2,3,4])
array_one


NameError: name 'np' is not defined

In [10]:
array_one = np.array([1,2,3,4])
array_one

NameError: name 'np' is not defined

In [11]:
import numpy as np

In [12]:
array_one = np.array([1,2,3,4])

array_one

array([1, 2, 3, 4])

In [13]:
type(array_one)

numpy.ndarray

In [14]:
# example:

In [15]:
numbers = [9,8,7,6]

In [16]:
array_two = np.array(numbers)

array_two

array([9, 8, 7, 6])

In [17]:
# note: array is very similar to a list

In [18]:
# but array has high performance because array's internal implementation of storing the data is optimized & retrives the data in a faster manner.

In [19]:
#creatin an array of zeroes with desired shape(x,y)

In [20]:
#where x is no. of rows
# y is no. of columns

In [21]:
array_of_zeroes = np.zeroes((3,4))

array_of_zeroes

AttributeError: module 'numpy' has no attribute 'zeroes'

In [22]:
array_of_zeroes = np.zeroes((3,4))
array_of_zeroes

AttributeError: module 'numpy' has no attribute 'zeroes'

In [23]:
import numpy as np

In [24]:
array_of_zeroes = np.zeroes((3,4))

array_of_zeroes

AttributeError: module 'numpy' has no attribute 'zeroes'

In [25]:
array_of_zeroes = np.zeroes((3,4))
array_of_zeroes

AttributeError: module 'numpy' has no attribute 'zeroes'

In [26]:
array_of_zeros = np.zeros((3,4))

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
array_of_ones = np.ones((4,5)) # array of ones

array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# internal implementation of an array is float (Decimals), integers and float (decimals)

In [29]:
# hence output comes as .

In [30]:
array_of_ones_int = np.ones((4,5), dtype=np.int16) # array of ones using int16 to avoid . in output

array_of_ones_int

SyntaxError: cannot assign to function call (<ipython-input-30-6a59e938788d>, line 1)

In [31]:
array_of_ones_int = np.ones((4,5), dtype=np.int16) # array of ones using int16 to avoid . in output

array_of_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [ ]:
------------********************---------------------