In [1]:
import numpy as np

In [2]:
#creating a empty array --------> empty array holds the information 

In [4]:
array_empty = np.empty((2,3))

array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_eye = np.eye((4))

array_eye                 # creating an idenity matrix of 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
array_eye = np.eye((3))

array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#req : want to put the numbers in an array till 20 

In [9]:
# arange function is used 

In [10]:
#  arange(startvalue,stopvalue,stepcount)  #last value is exclusive

In [11]:
x = np.arange(20)

x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
array_of_evens = np.arange(2,20,2)             

array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
array_of_floats = np.arange(0,3,0.3)

array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [17]:
# dimensions (x,y)

In [19]:
array_of_2d = np.array([(2,4,6),(3,5,7)])

array_of_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [21]:
array_of_2d = np.array([(2,4,6),(3,5,7)])       # shape tells its how many shape it has 


array_of_2d.shape

(2, 3)

In [22]:
array_of_2d = np.array([(2,4,6),(3,5,7)])    # ndim tell its how many dimensionals

array_of_2d.ndim

2

In [23]:
x = np.arange(6) # arange gives the output in linear format ie 1d array

x

array([0, 1, 2, 3, 4, 5])

In [24]:
x = np.arange(6).reshape(2,3) # reshape splits the output in 2d array

x

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
x = np.arange(6).reshape(3,2) # where x = 3 (vertical) and y = 2 (horizontal)

x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
# note: reshape value should be equal to arange value logic 3*2 =6 

In [27]:
# another example


In [30]:
x = np.arange(6).reshape(4,2)

x

ValueError: cannot reshape array of size 6 into shape (4,2)